### ISSUE TITLE
Feature request: Named numeric entities

### ISSUE THREAD

**Issue by WillAdams** [dune3d/dune3d#120] opened 2024-06-10 12:52 UTC
Each time that a constraint is provided as a dimension, it would be awesome to have it collected in a list of numeric entities which could then be referenced (by name) and edited (to include formulas which reference other values by their name) --- this would allow a full parametric experience, and the easy adjustment of a part/project to a given size.

**Comment by ruevs** [comment] 2024-06-10 17:28
https://github.com/dune3d/dune3d/discussions/83

**Comment by carrotIndustries** [comment] 2024-06-10 18:54
this is an almost exact duplicate of #117

**Closed by carrotIndustries** 2024-06-10 18:54 UTC
