### ISSUE TITLE
[Win] Item toggle has odd behavior

### ISSUE THREAD

**Issue by biggestsonicfan** [dune3d/dune3d#51] opened 2024-01-27 18:47 UTC
If opening the sample project with latest git as of this issue 290d011468720513ed6dc8ab44bcbb82c914f9ec and I highlight a Chamfer item:
![Screenshot 2024-01-27 103618](https://github.com/dune3d/dune3d/assets/9744201/571624f7-51da-4eb6-9f3f-663aafc80549)

Then proceed to click an item above the highlighted item (not clicking the checkbox), all items between the two are untoggled
![Screenshot 2024-01-27 103937](https://github.com/dune3d/dune3d/assets/9744201/6eb0cebf-652f-41b0-bc29-d7c4c926b0af)

Next, clicking on a specific item on the checkbox of the untoggled items now re-toggles all items between the two...
![Screenshot 2024-01-27 104016](https://github.com/dune3d/dune3d/assets/9744201/c7422a02-c06f-418b-be83-f221ac4e864c)

I've also taken a video to show the behavior in motion
https://github.com/dune3d/dune3d/assets/9744201/6b1524bd-ba9d-400a-9440-ae0f9180893f

Should the default behavior of clicking an item toggle all items below it?

**Comment by carrotIndustries** [comment] 2024-01-27 19:01
This is works as intended: https://docs.dune3d.org/en/latest/usage.html#groups

When looking at a group, all groups after it are out of scope.

**Closed by carrotIndustries** 2024-01-27 19:01 UTC

**Comment by biggestsonicfan** [comment] 2024-01-28 00:14
I'd really wish that were an option specifically, it's very jarring to work with in my opinion. But then again, I haven't gotten quite far with the program.
